development:
  GMAIL_USERNAME: diploma.fitu@gmail.com
  GMAIL_PASSWORD: guyyb789

test:
  GMAIL_USERNAME: diploma.fitu@gmail.com
  GMAIL_PASSWORD: guyyb789

production:
  GMAIL_USERNAME: diploma.fitu@gmail.com
  GMAIL_PASSWORD: guyyb789